export const locationFilter = [
  {
    filterType: "Location",
    array: [
      "Ahmedabad",
      "Ambala",
      "Amritsar",
      "Bangalore",
      "Bhopal",
      "Bhubaneswar",
      "Chennai",
      "Coimbatore",
      "Cuttack",
      "Delhi",
      "Ghaziabad",
      "Gurugram",
      "Hyderabad",
      "Indore",
      "Jaipur",
      "Kanpur",
      "Kochi",
      "Kolkata",
      "Lucknow",
      "Ludhiana",
      "Madurai",
      "Mangalore",
      "Mumbai",
      "Mysore",
      "Nagpur",
      "Noida",
      "Panaji",
      "Patna",
      "Pune",
      "Rajkot",
      "Ranchi",
      "Sambhajinagar",
      "Surat",
      "Thiruvananthapuram",
      "Udaipur",
      "Vadodara",
      "Vijayawada",
      "Visakhapatnam",
    ],
  },
];

export const industryFilter = [
  {
    filterType: "Industry",
    array: [
      "Frontend Developer",
      "Backend Developer",
      "Data Scientist",
      "FullStack Developer",
      "Nextjs Developer",
      "DevOps Engineer",
      "UI/UX Designer",
      "Mobile App Developer",
      "Machine Learning Engineer",
      "Cybersecurity Analyst",
      "Cloud Engineer",
      "AI Researcher",
      "Software Engineer",
      "Database Administrator",
      "Game Developer",
      "Blockchain Developer",
      "Site Reliability Engineer",
      "QA Engineer",
      "Systems Architect",
      "Product Manager",
      "Technical Support Engineer",
      "Network Engineer",
      "Data Analyst",
      "Embedded Systems Engineer",
      "Augmented Reality Developer",
      "Virtual Reality Developer",
      "IT Project Manager",
      "Salesforce Developer",
      "Technical Writer",
      "Big Data Engineer",
      "Scrum Master",
      "Solutions Architect",
      "Cloud Solutions Architect",
      "Site Reliability Engineer",
      "Agile Coach",
      "Data Engineer",
      "Network Security Engineer",
    ],
  },
];

export const salaryFilter = [
  {
    filterType: "Salary",
    array: [
      { range: "05 + LPA", value: "5" },
      { range: "10 + LPA", value: "10" },
      { range: "15 + LPA", value: "15" },
      { range: "20 + LPA", value: "20" },
    ],
  },
];

export const experienceFilter = [
  {
    filterType: "Experience",
    array: [
      { yoe: "1-2 Years", value: "1-2" },
      { yoe: "3-5 Years", value: "3-5" },
      { yoe: "6-8 Years", value: "6-8" },
      { yoe: "8-10 Years", value: "8-10" },
    ],
  },
];
